language : node_js
node_js:
 - "10"
os:
 - linux

jobs:
  include:
    - stage: github release
      deploy:
        script:
          - cd dist
          - ls
        provider: pages
        skip_cleanup: true
        github-token: "$github_TOKEN"
        local-dir: /vuti
        on:
          branch: master
