language : node_js
node_js:
 - "10"
os:
 - linux

jobs:
  include:
    - stage: github release
      deploy:
        provider: pages
        skip_cleanup: true
        github-token: "$github_TOKEN"
        local-dir: /
        on:
          branch: master
