language : node_js
node_js:
 - "10"
install:
- npm install
os:
 - linux

script: 
 - npm run build
 - ls

jobs:
  include:
    - stage: github release
      deploy:
        provider: pages
        skip_cleanup: true
        github-token: "$github_TOKEN"
        local-dir: /
        on:
          branch: master
